src/Entity/Personne.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity]
class Personne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $numero_tel = null;

    #[ORM\Column(type: "date")]
    private ?\DateTimeInterface $date_arrive = null;

    #[ORM\Column(type: "date", nullable: true)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column(length: 20)]
    /**
     * @Assert\Regex(
     *     pattern="/^(titulaire|ATER|Doctorant|Post-doctorant|Ingénieur|Secrétaire)$/",
     *     message="Le statut doit être 'titulaire', 'ATER', 'Doctorant', 'Post-doctorant', 'Ingénieur' ou 'Secrétaire'"
     * )
     */
    private ?string $statut = null;

    #[ORM\ManyToOne(targetEntity: Bureau::class, inversedBy: 'personnes')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Bureau $bureau = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNumeroTel(): ?string
    {
        return $this->numero_tel;
    }

    public function setNumeroTel(string $numero_tel): static
    {
        $this->numero_tel = $numero_tel;

        return $this;
    }

    public function getDateArrive(): ?\DateTimeInterface
    {
        return $this->date_arrive;
    }

    public function setDateArrive(\DateTimeInterface $date_arrive): static
    {
        $this->date_arrive = $date_arrive;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(?\DateTimeInterface $date_depart): static
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getBureau(): ?Bureau
    {
        return $this->bureau;
    }

    public function setBureau(?Bureau $bureau): static
    {
        $this->bureau = $bureau;

        return $this;
    }
}

src/Controller/AdminControllerPersonneController.php
<?php

namespace App\Controller;

use App\Entity\Personne;
use App\Form\PersonneType;
use App\Repository\PersonneRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/controller/personne')]
class AdminControllerPersonneController extends AbstractController
{
    #[Route('/', name: 'app_admin_controller_personne_index', methods: ['GET'])]
    public function index(PersonneRepository $personneRepository): Response
    {
        $personnes = $personneRepository->findAll();

        return $this->render('admin_controller_personne/index.html.twig', [
            'personnes' => $personnes,
        ]);
    }
    #[Route('/listeIndex', name: 'app_admin_controller_personne_liste_index', methods: ['GET'])]
    public function listeIndex(PersonneRepository $personneRepository): Response
    {
        $personnes = $personneRepository->findAll();

        return $this->render('admin_controller_personne/listeIndex.html.twig', [
            'personnes' => $personnes,
        ]);
    }

    #[Route('/new', name: 'app_admin_controller_personne_new', methods: ['GET', 'POST'])]
public function new(Request $request, EntityManagerInterface $entityManager): Response
{
    $personne = new Personne();
    $form = $this->createForm(PersonneType::class, $personne);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        // Vérifier si le bureau a atteint sa capacité maximale
        $bureau = $personne->getBureau();
        if ($bureau) {
            $repository = $entityManager->getRepository(Personne::class);
            $queryBuilder = $repository->createQueryBuilder('p');
            $queryBuilder
                ->where('p.bureau = :bureau')
                ->setParameter('bureau', $bureau);
            $query = $queryBuilder->getQuery();
            $countPersons = count($query->getResult());//On compte le nombre de bureau 
    
            if ($countPersons >= $bureau->getNombPlace()) {
                $this->addFlash('error', 'Le bureau a atteint sa capacité maximale de personnes.');
                return $this->redirectToRoute('app_admin_controller_personne_index');
            }
        }
    
        $entityManager->persist($personne);
        $entityManager->flush();
    
        return $this->redirectToRoute('app_admin_controller_personne_index', [], Response::HTTP_SEE_OTHER);
    }
    

    return $this->render('admin_controller_personne/new.html.twig', [
        'personne' => $personne,
        'form' => $form->createView(),
    ]);
}


    #[Route('/{id}', name: 'app_admin_controller_personne_show', methods: ['GET'])]
    public function show(Personne $personne): Response
    {
        return $this->render('admin_controller_personne/show.html.twig', [
            'personne' => $personne,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_controller_personne_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Personne $personne, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PersonneType::class, $personne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_controller_personne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_controller_personne/edit.html.twig', [
            'personne' => $personne,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_admin_controller_personne_delete', methods: ['POST'])]
    public function delete(Request $request, Personne $personne, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($personne);
        $entityManager->flush();
    
        return $this->redirectToRoute('app_admin_controller_personne_index', [], Response::HTTP_SEE_OTHER);
    }
    
}

templates/admin_controller_personne/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_controller_personne_delete', {'id': personne.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personne.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/admin_controller_personne/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/admin_controller_personne/edit.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Modifier une personne</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="asset/css/admin_conEdit.css"  />
    <link rel="icon" type="image/png" href="image/imgU.jpg">

    <style>
        
    </style>
</head>
<body>
    {% block body %}
        <div class="container">
            <h1>Modifier une personne</h1>

            <!-- Début du formulaire -->
            {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
                {% for field in form %}
                {% if field.vars.name != '_token' %}
                <span class="field-name">{{ field.vars.name }}</span>
                    <div class="form-group">
                            {{ form_widget(field, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    {% endif %}
                {% endfor %}
                <!-- Boutons de soumission et de suppression -->
                <div class="form-group d-flex justify-content-end">
                    <div class="mr-auto">
                        <a href="{{ path('app_admin_controller_personne_index') }}" class="btn btn-secondary mr-2">Retour à la liste</a>
                    <button type="submit" class="btn btn-primary">{{ button_label|default('Mettre à jour') }}</button>
                    <button type="submit" class="btn btn-danger ml-2" formaction="{{ path('app_admin_controller_personne_delete', {'id': personne.id}) }}">Supprimer</button>
            <!-- Fin du formulaire -->
            {{ form_end(form) }}
            <a href="/menu" class="btn btn-secondary">Administration</a>
        </div>
    {% endblock %}
    <!-- Scripts JavaScript nécessaires -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/admin_controller_personne/index.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Index des personnes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="asset/css/admin_conIndex.css"  />
    <link rel="icon" type="image/png" href="image/imgU.jpg">

    <style></style>
</head>
<body>

<div class="container">
    <h1>Index des personnes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Numéro de téléphone</th>
                <th>Date d'arrivée</th>
                <th>Date de départ</th>
                <th>Statut</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for personne in personnes %}
            <tr>
                <td>{{ personne.id }}</td>
                <td>{{ personne.nom }}</td>
                <td>{{ personne.prenom }}</td>
                <td>{{ personne.numeroTel }}</td>
                <td>{{ personne.dateArrive ? personne.dateArrive|date('Y-m-d') : '' }}</td>
                <td>{{ personne.dateDepart ? personne.dateDepart|date('Y-m-d') : '' }}</td>
                <td>
                    {% if personne.statut == 'titulaire' %}
                        Titulaire
                    {% elseif personne.statut == 'ATER' %}
                        ATER
                    {% elseif personne.statut == 'Doctorant' %}
                        Doctorant
                    {% elseif personne.statut == 'Post-doctorant' %}
                        Post-doctorant
                    {% elseif personne.statut == 'Ingénieur' %}
                        Ingénieur
                    {% elseif personne.statut == 'Secrétaire' %}
                        Secrétaire
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('app_admin_controller_personne_show', {'id': personne.id}) }}" class="btn btn-primary">Voir</a>
                    <a href="{{ path('app_admin_controller_personne_edit', {'id': personne.id}) }}" class="btn btn-secondary">Modifier</a>
                </td>

            </tr>
            
            {% else %}
            <tr>
                <td colspan="8">Aucun enregistrement trouvé</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
                <a href="/menu" class="btn btn-secondary">Administration</a>


    {# <a href="{{ path('app_admin_controller_personne_new') }}" class="btn btn-success">Créer un nouveau</a> #}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/admin_controller_personne/listeIndex.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Index des personnes</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="asset/css/admin_conListInd.css"  />
    <link rel="icon" type="image/png" href="image/imgU.jpg">

    <style>
       
    </style>
</head>
<body>

<div class="container">
    <h1>Liste des personnes triées par prénoms</h1>

    <table class="table">
    <thead>
        <tr>
            <th>Index</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Numéro de téléphone</th>
            <th>Date d'arrivée</th>
            <th>Date de départ</th>
            <th>Statut</th>
        </tr>
    </thead>
    <tbody>
        {% for personne in personnes|sort((a, b) => a.prenom <=> b.prenom) %} {# Trie les personnes par prénom #}
            <tr>
                <td>{{ loop.index }}</td> {# Affiche l'index de la boucle au lieu d'utiliser une variable i #}
                <td>{{ personne.nom }}</td>
                <td>{{ personne.prenom }}</td>
                <td>{{ personne.numeroTel }}</td>
                <td>{{ personne.dateArrive ? personne.dateArrive|date('Y-m-d') : '' }}</td>
                <td>{{ personne.dateDepart ? personne.dateDepart|date('Y-m-d') : '' }}</td>
                <td>
                    {% if personne.statut == 'titulaire' %}
                        Titulaire
                    {% elseif personne.statut == 'ATER' %}
                        ATER
                    {% elseif personne.statut == 'Doctorant' %}
                        Doctorant
                    {% elseif personne.statut == 'Post-doctorant' %}
                        Post-doctorant
                    {% elseif personne.statut == 'Ingénieur' %}
                        Ingénieur
                    {% elseif personne.statut == 'Secrétaire' %}
                        Secrétaire
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun enregistrement trouvé</td> {# Utilise colspan="7" au lieu de colspan="8" car il y a 7 colonnes dans le tableau #}
            </tr>
        {% endfor %}
    </tbody>
</table>

    <button><a href="/pdf/generate">Télécharger la liste de personnes</a></button>
    <button><a href="/pdf/generateGroupe">Télécharger la liste de personnes par groupe</a></button>
    <button><a href="/menu">Administration</a></button>
    {# <a href="{{ path('app_admin_controller_personne_new') }}" class="btn btn-success">Créer un nouveau</a> #}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/admin_controller_personne/new.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Ajouter une nouvelle personne</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="asset/css/admin_conNew.css"  />
    <link rel="icon" type="image/png" href="image/imgU.jpg">

    <style></style>
</head>
<body>

<div class="container">
    <h1>Ajouter une nouvelle personne</h1>

    {{ form_start(form) }}
        {% for field in form %}
            {% if field.vars.name != 'id' and field.vars.name != '_token' %}
                <span class="field-name">{{ field.vars.name }}</span>

                     
                <div class="form-group">
                    <div class="col-sm-10">
                        {{ form_widget(field, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Ajouter</button>
        <a href="{{ path('app_admin_controller_personne_index') }}" class="btn btn-secondary">Retour à la liste</a>
        <a href="/menu" class="btn btn-secondary">Administration</a>
    {{ form_end(form) }}

</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/admin_controller_personne/show.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Personne</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="icon" type="image/png" href="image/imgU.jpg">

    <style>
        /* Styles personnalisés pour la page */
        .table-bordered th,
        .table-bordered td {
            border: 1px solid #dee2e6;
        }
        .table-bordered th {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Personne</h1>

        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ personne.id }}</td>
                </tr>
                <tr>
                    <th>Nom</th>
                    <td>{{ personne.nom }}</td>
                </tr>
                <tr>
                    <th>Prénom</th>
                    <td>{{ personne.prenom }}</td>
                </tr>
                <tr>
                    <th>Numéro de téléphone</th>
                    <td>{{ personne.numeroTel }}</td>
                </tr>
                <tr>
                    <th>Date d'arrivée</th>
                    <td>{{ personne.dateArrive ? personne.dateArrive|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Date de départ</th>
                    <td>{{ personne.dateDepart ? personne.dateDepart|date('Y-m-d') : '' }}</td>
                </tr>
                <tr>
                    <th>Statut</th>
                    <td>{{ personne.statut }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('app_admin_controller_personne_index') }}" class="btn btn-secondary mr-2">Retour à la liste</a>
        <a href="{{ path('app_admin_controller_personne_edit', {'id': personne.id}) }}" class="btn btn-primary">Modifier</a>
        <a href="/menu" class="btn btn-secondary">Administration</a>

    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>